use spring_db;

insert into products (name, price_in_cents) values ('Dark-winged trumpeter', 8707);
insert into products (name, price_in_cents) values ('Cockatoo, red-breasted', 9310);
insert into products (name, price_in_cents) values ('Hawk, galapagos', 8236);
insert into products (name, price_in_cents) values ('Brocket, red', 1768);
insert into products (name, price_in_cents) values ('Otter, canadian river', 1262);
insert into products (name, price_in_cents) values ('Griffon vulture', 4107);
insert into products (name, price_in_cents) values ('Wildebeest, blue', 112);
insert into products (name, price_in_cents) values ('Bustard, denham''s', 9599);
insert into products (name, price_in_cents) values ('Swan, black', 5340);
insert into products (name, price_in_cents) values ('Bird, secretary', 406);
insert into products (name, price_in_cents) values ('Gerenuk', 2413);
insert into products (name, price_in_cents) values ('Dolphin, bottle-nose', 8347);
insert into products (name, price_in_cents) values ('Bushbaby, large-eared', 7671);
insert into products (name, price_in_cents) values ('Fox, crab-eating', 9525);
insert into products (name, price_in_cents) values ('Azara''s zorro', 5071);
insert into products (name, price_in_cents) values ('Kelp gull', 2669);
insert into products (name, price_in_cents) values ('River wallaby', 914);
insert into products (name, price_in_cents) values ('Wolf, common', 7490);
insert into products (name, price_in_cents) values ('Crab-eating fox', 2470);
insert into products (name, price_in_cents) values ('Crane, sandhill', 7247);
insert into products (name, price_in_cents) values ('Water moccasin', 2339);
insert into products (name, price_in_cents) values ('Frilled lizard', 2172);
insert into products (name, price_in_cents) values ('Tinamou, elegant crested', 8850);
insert into products (name, price_in_cents) values ('Cliffchat, mocking', 6719);
insert into products (name, price_in_cents) values ('Skunk, western spotted', 270);
insert into products (name, price_in_cents) values ('Skink, african', 8677);
insert into products (name, price_in_cents) values ('Feathertail glider', 4029);
insert into products (name, price_in_cents) values ('African red-eyed bulbul', 7411);
insert into products (name, price_in_cents) values ('Skunk, striped', 4559);
insert into products (name, price_in_cents) values ('Savannah deer', 6413);
insert into products (name, price_in_cents) values ('Wapiti, elk,', 1843);
insert into products (name, price_in_cents) values ('Snake, western patch-nosed', 3970);
insert into products (name, price_in_cents) values ('Common palm civet', 9484);
insert into products (name, price_in_cents) values ('Lizard, frilled', 6681);
insert into products (name, price_in_cents) values ('Red deer', 4696);
insert into products (name, price_in_cents) values ('Otter, brazilian', 4385);
insert into products (name, price_in_cents) values ('Seal, northern fur', 2212);
insert into products (name, price_in_cents) values ('Bobcat', 7053);
insert into products (name, price_in_cents) values ('Heron, black-crowned night', 8816);
insert into products (name, price_in_cents) values ('Mongoose, banded', 7416);
insert into products (name, price_in_cents) values ('Gull, silver', 4776);
insert into products (name, price_in_cents) values ('American marten', 4803);
insert into products (name, price_in_cents) values ('Eagle, long-crested hawk', 90);
insert into products (name, price_in_cents) values ('Topi', 8708);
insert into products (name, price_in_cents) values ('Gorilla, western lowland', 3993);
insert into products (name, price_in_cents) values ('Vulture, oriental white-backed', 7494);
insert into products (name, price_in_cents) values ('Southern sea lion', 7218);
insert into products (name, price_in_cents) values ('Kudu, greater', 1976);
insert into products (name, price_in_cents) values ('Arctic fox', 9086);
insert into products (name, price_in_cents) values ('Lappet-faced vulture', 1968);


insert into users (id, email, password, username) values (1, 'domo@email.com', 'password', 'domo');